### ISSUE TITLE
[Question] What's the frequency of updating the DDNS?

### ISSUE THREAD

**Issue by vincentcox** [oznu/docker-cloudflare-ddns#11]
I was wondering if it was possible to pass the time interval as a parameter or what the frequency of the updates are now by default.

**Comment by oznu** [comment]
The job runs every five minutes and on container restart. Currently not configurable.

This is the line that sets the cron:

https://github.com/oznu/docker-cloudflare-ddns/blob/master/root/etc/cont-init.d/30-cloudflare-setup#L77

**Comment by vincentcox** [comment]
Thanks, exactly what I needed to know. Closing this issue.
