### ISSUE TITLE
Multiple subdomains do not update

### ISSUE THREAD

**Issue by f0rkth1s** [oznu/docker-cloudflare-ddns#16]
I have added multiple subdomains in unraid to this container, only the domain and last listed subdomain actually update.

I have added the subdomains as additional optional entries in unraid.

Is this a known issue or am I perhaps doing it wrong?

Thanks

**Comment by oznu** [comment]
Only a single subdomain entry is permitted. You can use CNAMEs for other domains that need the same IP address.

https://github.com/oznu/docker-cloudflare-ddns#multiple-domains
