### ISSUE TITLE
Idea: Multi-arch images

### ISSUE THREAD

**Issue by jamct** [oznu/docker-cloudflare-ddns#18]
I would suggest to switch to multi-arch docker images. They contain a manifest and can contain images for multiple architectures and the docker daemon will pull the correct one. With multi-arch you do not have to specify a tag like `armhf`.

**Comment by oznu** [comment]
Hey @jamct,

This should already be the case as I did this a few weeks ago.

See the latest tag has multiple arch options:

https://hub.docker.com/layers/oznu/cloudflare-ddns/latest/images/sha256-1f0158f2af7f9d013314cc62578e812372ae713574574e98c67af36479e53213

**Comment by jamct** [comment]
Hey @oznu,

you are right, it already is a multistage image. Just needs a hint in the docs. I will prepare a PR with a fix for Readme.md.

**Comment by oznu** [comment]
Readme updated.
