### ISSUE TITLE
Rpi3: Dig not working

### ISSUE THREAD

**Issue by tynor88** [oznu/docker-cloudflare-ddns#2]
Hi,

Thanks for building this, however I don't get any IP back when running on RPI 3?

> dig @resolver1.opendns.com myip.opendns.com A

yields nothing inside the container.

So i get all these lines:

> Updating CloudFlare DNS recordmy.domain.com from XX.XXX.XXX.XX to ...
ERROR: Failed to update CloudFlare DNS record recordmy.domain.com from XX.XXX.XXX.XX to

Is it a bug in the Rpi 3 image?

**Comment by oznu** [comment]
Hi @tynor88,

I've made a small change that will make the container fallback to a http ip address lookup if the dns method fails to return a result.

https://github.com/oznu/docker-cloudflare-ddns/commit/b54d4294d83defb55da73b2b40484439110c4521

**Comment by tynor88** [comment]
Hi @oznu 

That was quick 👍 Works great now!

> CloudFlare DNS record my.domain.com (XX.XXX.XXX.XX) updated successfully.
