### ISSUE TITLE
Req: Add env variable to set A Record TTL

### ISSUE THREAD

**Issue by projx** [oznu/docker-cloudflare-ddns#23]
Hi

It looks like the TTL is always set to 3hrs, even if I manually set this in the Cloudflare Web UI to 2 minutes, the script resets it to 3hrs each time it updates.

Could you add an environmental variable, so we can specify what the TTL should be set too?

Thanks

**Comment by JakeWharton** [comment]
This could potentially be mitigated by switching to use HTTP PATCH instead of HTTP POST in the script.

https://api.cloudflare.com/#dns-records-for-a-zone-patch-dns-record

**Comment by oznu** [comment]
The TTL was being set to 180 after a recent update.

I've made a change so that created records will now have the TTL set to "Auto" and the update record method does not change the TTL from what is set in CloudFlare.
