### ISSUE TITLE
release diifferent arch in same tag

### ISSUE THREAD

**Issue by zh99998** [oznu/docker-cloudflare-ddns#25]
could you release all arch in `latest` tag ?
docker support multiple arch in same tag. client can choose correct one automaticly.

release them in same tag makes deploy easier. I can use exact same config to deploy to all my nodes whatever its arch.

per-arch tags may still be kept for backwards compatibility

**Comment by oznu** [comment]
I do this already.

**Comment by zh99998** [comment]
ahh ok. sorry .

**Comment by oznu** [comment]
See https://hub.docker.com/r/oznu/cloudflare-ddns/tags
