### ISSUE TITLE
Multiple subdomains

### ISSUE THREAD

**Issue by MrSejlund** [oznu/docker-cloudflare-ddns#26]
Love the application! But how do i use it for multiple subdomains? 

Comma separated doesn't seem to work :-)

**Comment by oznu** [comment]
Hi @MrSejlund,

You can setup CNAMEs in CloudFlare control panel.

```
another.example.com CNAME ddns.example.com
```

**Comment by oznu** [comment]
https://www.cloudflare.com/learning/dns/dns-records/dns-cname-record/

**Comment by MrSejlund** [comment]
Just saw the closed issue with a similar title. Thanks :-)
