### ISSUE TITLE
Help troubleshooting this error

### ISSUE THREAD

**Issue by lordraiden** [oznu/docker-cloudflare-ddns#28]
How can I fix this? I have been hardening Cloudflare condiguration, the firewall is not blocking anything but is possible that some setting (TLS 1.3, HTTPS force...) is breaking the IP sync?

> [cont-init.d] 50-ddns: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting crond...
crond: crond (busybox 1.31.1) started, log level 6
[services.d] done.
crond: USER root pid 248 cmd /etc/cont-init.d/50-ddns
Updating CloudFlare DNS record XXXX.from XXXXX to ;; connection timed out; no servers could be reached...
Updating CloudFlare DNS record XXXXXX from XXXXXXX to ;; connection timed out; no servers could be reached...
ERROR: Failed to update CloudFlare DNS record XXXXXXXX from XXXXXto ;; connection timed out; no servers could be reached

**Comment by clevernyyyy** [comment]
FYI - I just got this error too.  You wouldn't happen to be using Century Link or ATT would you?

https://www.reddit.com/r/centurylink/comments/8jq0kx/centurylink_wont_route_to_cloudflare_dns_1111/

You can probably edit [this line](https://github.com/oznu/docker-cloudflare-ddns/blob/master/root/app/cloudflare.sh#L33), to something like this:

```
IP_ADDRESS=$(dig +short myip.opendns.com @resolver1.opendns.com | tr -d '"')
```

**Comment by clevernyyyy** [comment]
Hopefully this addresses the issue:  https://github.com/oznu/docker-cloudflare-ddns/pull/30
