### ISSUE TITLE
Multiple zones?

### ISSUE THREAD

**Issue by cbrooker** [oznu/docker-cloudflare-ddns#29]
Hi,

Is it possible to update multiple zones (Domains) with a single cloudflare-ddns instance?
At the moment I'm running multiple containers, 1 for each domain, which feels like a lot of overhead.

Is this something that could be added?

**Comment by oznu** [comment]
Could you use CNAMEs?

**Comment by cbrooker** [comment]
I guess, I could. Something about it feels a little dirty/hacky. But it's best solution at the moment.

Thanks.
