### ISSUE TITLE
multiple subdomains

### ISSUE THREAD

**Issue by tuananh** [oznu/docker-cloudflare-ddns#32]
many homelab use a reserve proxy to proxy local apps at home. For that, they will need multiple domains to update to the same home ip.

are you open to accept such merge request?

i was thinking maybe use SUBDOMAIN with comma separated?

```
-e SUBDOMAIN=subdomain1,subdomain2,subdomain3 \
```

**Comment by oznu** [comment]
CNAMEs are the way to go here.

https://github.com/oznu/docker-cloudflare-ddns/issues/26

**Comment by tuananh** [comment]
Thanks.
