### ISSUE TITLE
multiple subdomains?

### ISSUE THREAD

**Issue by tc60045** [oznu/docker-cloudflare-ddns#33]
Love this container - was using a different one, was unaware of the new scoped API keys, got frustrated, found yours, setup was 30 seconds -- thank you.

Not necessary for me at the moment, but if you could consider making it possible to update multiple subdomains, I would appreciate it.

**Comment by juan11perez** [comment]
already answered as such:

CNAMEs are the way to go here.

#26

https://www.cloudflare.com/learning/dns/dns-records/dns-cname-record/

**Comment by tc60045** [comment]
Juan, you are right - thanks!
