### ISSUE TITLE
Support .cf, .ga, .gq, .ml, or .tk TLD (top-level domain)

### ISSUE THREAD

**Issue by GuyKh** [oznu/docker-cloudflare-ddns#36]
When trying to run the API manually - I'm getting
```
{
  "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
}
```

And indeed i'm using a tk domain.

Is there any way to make this work?

**Comment by GuyKh** [comment]
It seems like a bug/feature on Cloudflare end
https://community.cloudflare.com/t/unable-to-update-ddns-using-api-for-some-tlds/167228/49

**Comment by gardner** [comment]
This has been working for my `.tk` domain until recently.

**Comment by gardner** [comment]
It was an intentional change by cloudflare: https://community.cloudflare.com/t/unable-to-update-ddns-using-api-for-some-tlds/167228

**Comment by GuyKh** [comment]
> This has been working for my `.tk` domain until recently.

Yeah, look at the link I put. It's a few days problem

**Comment by RUGMJ7443** [comment]
hey is there any update on this?

**Comment by chessmango** [comment]
> hey is there any update on this?

Pretty well beyond anything this project can do really. Cloudflare themselves are curbing potential abuse by blocking API modification for freebie TLDs. A bit heavy-handed perhaps, but abuse-prevention is a tricky business.

**Comment by jjasoncool** [comment]
![圖片](https://user-images.githubusercontent.com/24731867/155629514-d1d915b8-4812-4320-9c3b-3b8c5ce0e15d.png)
Maybe is a solution.
I haven't try it.

resource: https://community.cloudflare.com/t/unable-to-update-ddns-using-api-for-some-tlds/167228/65

**Comment by GuyKh** [comment]
@jjasoncool I've actually created a single CNAME route (`abc.tk -> abc.duckdns.org`)
and created all other subdomains are routed to the main TK. (`my.abc.tk -> abc.tk`)
