### ISSUE TITLE
DNS record for XYZ.cf was not found in XYZ.cf zone.  creating now... ERROR

### ISSUE THREAD

**Issue by Gnollo** [oznu/docker-cloudflare-ddns#39]
I use unraid and installed the Cloudflare-ddns docker, but i am getting this error message.
I created a custo API Token, and pasted it in the config. Got the first error message, was asked to removed the email record, done that and this is the new error message I get in the log.
PS I replaced my actual address with XYZ 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-cloudflare-setup: executing...
DNS Zone: XYZ.cf (lotsofnumbers)
DNS record for 'XYZ.cf' was not found in XYZ.cf zone. Creating now...
----------------------------------------------------------------
ERROR: Failed to create DNS record 'XYZ.cf'

----------------------------------------------------------------
[cont-init.d] 30-cloudflare-setup: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 50-remove-record: executing...
[cont-finish.d] 50-remove-record: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by oznu** [comment]
See https://github.com/oznu/docker-cloudflare-ddns/issues/36

CloudFlare is preventing API access to .cf domains.

**Comment by Gnollo** [comment]
Ok so no way for me to use this app to get it to auto-update?

**Comment by oznu** [comment]
I think so
