### ISSUE TITLE
Proxied IP instead correct Ip

### ISSUE THREAD

**Issue by shark2380** [oznu/docker-cloudflare-ddns#43]
Good morning,
i'm trying to set it up on raspberry pi4, but it update the A record with the proxied ip instead the reeal wan ip. How do i solved it?

Thanks in advance
Shark

**Comment by shark2380** [comment]
UPDATE,
in a rough way i have modified the script keeping only the line giving me the right IP address.

**Comment by rotordock** [comment]
I'm getting the same issue, updating with proxied IP instead of wan IP. Any idea how to fix this?

**Comment by LJRH** [comment]
Same issue: Raspberry pi 4, ubuntu 20.04 using docker-compose with the latest tag.

**Comment by rotordock** [comment]
adding this was the fix for me;

-e CUSTOM_LOOKUP_CMD=curl -sf4 https://ipinfo.io | jq -r '.ip'

**Comment by dbrennand** [comment]
I also fixed my issue in a similar method to @rotordock. I added the following environment variable for public IP lookup:

`-e CUSTOM_LOOKUP_CMD="curl 'https://api.ipify.org?format=json' | jq -r '.ip'"`

**Comment by shark2380** [comment]
After all this homemade fix I close the issue. Hope that the manteiner take a hint on how to improve him code for everyone. I don't know how to update it on github
