### ISSUE TITLE
Explain cron option 

### ISSUE THREAD

**Issue by andlil** [oznu/docker-cloudflare-ddns#48]
It is not entirely clear from the documentation how the CRON-option is used. 
I have tried - CRON="@hourly" in my docker-compose.yml (doesn't work and gives no error message) and I've tried -CRON="*/20 * * * *" which fails with a parsing error. 

Any hints?

**Comment by surrettcharles** [comment]
the CRON pattern needs to be tab separated, not space separated.

**Comment by andlil** [comment]
Aww, that sucks because you are not allowed to use tabs in YAML which means I cannot use docker-compose to run the container.

ERROR: yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "./docker-compose.yml", line 11, column 18

**Comment by Dulanic** [comment]
You should also be able to wrap it in quotes without using a seperate .env file.
