### ISSUE TITLE
Does this change the IPv4 or IPv6 record?

### ISSUE THREAD

**Issue by jwillmer** [oznu/docker-cloudflare-ddns#5]
I have a DS-Lite (dual stack) connection so that the IPv4 can't be used since I can't open IPv4 ports. How can I configure that this docker image only updates the IPv6 record in cloudflare?

**Comment by oznu** [comment]
Hi,

Presently this only project only does IPv4.

Happy to accept a PR to add support for AAAA / IPv6 records. My network isn't setup for IPv6 at the moment so it's difficult test.

**Comment by jwillmer** [comment]
I could test it for you. With DS-Lite you only get a shared IPv4 thats why it is a problem to use/set the IPv4 in cloudflare.

**Comment by jwillmer** [comment]
Your script looks fairly easy, I see the fastest way for me is to replace the IPv4 lookup with IPv6 lookup and post the new IP to record `AAA` instead of `A`.
More work is needed to create a config to define if I like to update IPv4 or IPv6 or both.

**Comment by oznu** [comment]
I don't think ipinfo.io supports IPv6 self-lookups, the dns record has no AAAA records as far as I can tell.

Can you see if this command works?

```
dig +short @resolver1.opendns.com myip.opendns.com AAAA
```

**Comment by oznu** [comment]
Never mind, tested that command on a vps. It does not work.

**Comment by oznu** [comment]
See https://github.com/oznu/docker-cloudflare-ddns#ipv6

The message there is very important:

> You need to run docker with IPv6 support, or run the container with host networking enabled.

Running the container with host networking (on a host that can resolve IPv6 directly) is probably easier than enabling docker IPv6 support. To do this just add `--net=host` to your docker run command, or `network_mode: host` to your docker-compose.yml.

**Comment by jwillmer** [comment]
wow, that was fast - very cool! For me this is all I need but I guess there are user with an IPv4 and an IPv6 that they want to refresh at the same time. I still close this issue since my use case works 👍

**Comment by oznu** [comment]
I thought of adding both IPv4 and IPv6 support simultaneously, but that would require a bit more work to keep track of the AAAA and A record IDs at the same time.

A project for later :)

**Comment by jwillmer** [comment]
The IPv6 is not fixed since your query provider does not support IPv6. You need to use a provide that returns you an IPv6 like:

```
curl --ipv6 https://myonlineportal.net/checkip
// curl --ipv4 https://myonlineportal.net/checkip

curl --ipv6 --url 'https://ipv6.nsupdate.info/myip'
```

**Comment by oznu** [comment]
Both providers I added for IPv6 support IPv6:

```shell
# primary
curl -sf6 https://ifconfig.co

# backup
curl -sf6 https//diagnostic.opendns.com/myip
```

**Comment by oznu** [comment]
Did you enable IPv6 on the docker daemon? Otherwise add `network_mode: host` to your docker-compose.yml:

https://github.com/oznu/docker-cloudflare-ddns/issues/5#issuecomment-392521600

**Comment by jwillmer** [comment]
Works as intended 👍 
Maybe you can add that info to Readme or create a demo docker-compose file?

**Comment by jwillmer** [comment]
I noticed you did but it didn't `stand out` - sorry, my bad!

**Comment by oznu** [comment]
Good to see it working.

I'll catch the error at runtime and output / explain the fix in the container logs.

**Comment by jwillmer** [comment]
Small note:

> You must be running Docker with IPv6 support enabled or you need to enable host networking on this container.
