### ISSUE TITLE
Update subdomain only

### ISSUE THREAD

**Issue by mtompkins** [oznu/docker-cloudflare-ddns#52]
It would be useful if an ability to only update a subdomain was made available. I didn't see any manner in which to not update the primary record/root domain.

**Comment by ServusNL** [comment]
Wait what? There is a "-e SUBDOMAIN" parameter right which does exactly that.

-e SUBDOMAIN - A subdomain of the ZONE to write DNS changes to. If this is not supplied the root zone will be used.

**Comment by mtompkins** [comment]
When I used that parameter the root was also updated.

**Comment by ServusNL** [comment]
I implemented it today and it work fine. where the local domain is: subdomain.subdomain2 and the zone = domain.nl. so the subdomain is without domain.nl. This works for me.

**Comment by mtompkins** [comment]
I used zone=acme.com subdomain=subdomain and both the subdomain A record and the zone A record were updated.
