### ISSUE TITLE
Usage with several subdomains

### ISSUE THREAD

**Issue by Manuel5cc** [oznu/docker-cloudflare-ddns#53]
I have tried using it with several subdomain, adding the "SUBDOMAIN" environment variable for each one, but it does only update one of them. Is this even a possibility? is it planned? if not I strongly suggest it.

**Comment by Phyremaster** [comment]
While running multiple containers is a solution, I too would like this feature for the sake of optimization.

**Comment by timmillwood** [comment]
I have a single domain I update, then cname all others to that.

**Comment by oznu** [comment]
> I have a single domain I update, then cname all others to that.

This is the correct way to do multiple domains.

https://www.cloudflare.com/en-au/learning/dns/dns-records/dns-cname-record/

https://community.cloudflare.com/t/how-do-i-add-a-cname-record/59
