### ISSUE TITLE
Help with this error

### ISSUE THREAD

**Issue by Seferovic8** [oznu/docker-cloudflare-ddns#55]
Hello, I am trying to use this script but i always get error:
cloudflare-ddns_1  | ERROR: Failed to update CloudFlare DNS record example.ml from Y.Y.Y.Y to X.X.X.X

cloudflare-ddns_1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
cloudflare-ddns_1  | [s6-init] ensuring user provided files have correct perms...exited 0.
cloudflare-ddns_1  | [fix-attrs.d] applying ownership & permissions fixes...
cloudflare-ddns_1  | [fix-attrs.d] done.
cloudflare-ddns_1  | [cont-init.d] executing container initialization scripts...
cloudflare-ddns_1  | [cont-init.d] 30-cloudflare-setup: executing...
cloudflare-ddns_1  | DNS Zone: example.ml (189a359456502834321a727pxksl3h2s)
cloudflare-ddns_1  | DNS Record: example.ml (a97ba1f2d4161afc8f22c18a198kj12m)
cloudflare-ddns_1  | [cont-init.d] 30-cloudflare-setup: exited 0.
cloudflare-ddns_1  | [cont-init.d] 50-ddns: executing...
cloudflare-ddns_1  | Updating CloudFlare DNS record example.ml from Y.Y.Y.Y to X.X.X.X...
cloudflare-ddns_1  | ERROR: Failed to update CloudFlare DNS record example.ml from Y.Y.Y.Y to X.X.X.X
cloudflare-ddns_1  | [cont-init.d] 50-ddns: exited 0.
cloudflare-ddns_1  | [cont-init.d] done.
cloudflare-ddns_1  | [services.d] starting services
cloudflare-ddns_1  | Starting crond...
cloudflare-ddns_1  | crond: crond (busybox 1.31.1) started, log level 6
cloudflare-ddns_1  | [services.d] done.

**Comment by ank0m** [comment]
I've the same problem.

**My docker-compose.yml:**
version: '2'
services:
  cloudflarae-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: always
    environment:
      - API_KEY=MY_API_KEY
      - ZONE=MY-DOMAIN.COM
      - PROXIED=false
      - PUID=1000
      - PGID=100
      - TZ=Europe/Berlin

=============================================================

**Docker container log:**
 [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
  [s6-init] ensuring user provided files have correct perms...exited 0.
  [fix-attrs.d] applying ownership & permissions fixes...
  [fix-attrs.d] done.
  [cont-init.d] executing container initialization scripts...
  [cont-init.d] 30-cloudflare-setup: executing... 
  DNS Zone: MY-DOMAIN.COM (f581db51a5c929f45b8e71f915e2497d)
  DNS Record: MY-DOMAIN.COM (6433f13d1a2862d47c5dbe67a856fc4f)
  [cont-init.d] 30-cloudflare-setup: exited 0.
  [cont-init.d] 50-ddns: executing... 
  Updating CloudFlare DNS record MY-DOMAIN.COM from CURRENT_DDNS_IP to ;; connection timed out; no servers could be reached...
  ERROR: Failed to update CloudFlare DNS record MY-DOMAIN.COM from CURRENT_DDNS_IP to ;; connection timed out; no servers could be reached
  [cont-init.d] 50-ddns: exited 0.
  [cont-init.d] done.
  [services.d] starting services
  Starting crond...
  crond: crond (busybox 1.31.1) started, log level 6
  [services.d] done.

**Comment by chicungunya** [comment]
Exactly the same error !
Did you find a solution ? 
Thanks guys

**Comment by chicungunya** [comment]
Guys, I think I found the solution : 

Check the log file and find the error message: “error”: "You cannot use this API for domains (top-level domains) with .cf, .ga, .gq, .ml or .tk TLDs. DNS settings for this domain, please Use the Cloudflare dashboard.

So if you have a domain like this, it's impossible to use the API for these domains. And only Cloudflare can change this. Do you confirm @oznu ?

**Comment by Seferovic8** [comment]
No, in my log file I only get this error
ERROR: Failed to update CloudFlare DNS record example.ml from X.X.X.X to Y.Y.Y.Y

**Comment by chicungunya** [comment]
Yes me too but if you have ml domain, it will never work. That's my point. cf, .ga, .gq, .ml or .tk does not work to upload cloudflare DNS

**Comment by gkchim** [comment]
i have the same issue

**Comment by Masterpayneio** [comment]
Curious, similar errors to mine. This seams to happen every year around this time. Also found this if it helps anyone. "The DNS API cannot be used for domains with .cf, .ga, .gq, .ml, or .tk TLDs." -Unfixable-
