### ISSUE TITLE
Cannot index array with string "content"

### ISSUE THREAD

**Issue by ptah4i** [oznu/docker-cloudflare-ddns#56]
Hey guys. I get this error 

jq: error (at <stdin>:0): Cannot index array with string "content"

Any help?

**Comment by ptah4i** [comment]
Solved. I use a domain with special characters (IDN / .de) like ö, ü or ä. 
Converting the IDN to ACE-String solved this error. 

Example:
IDN-Form: überall-ist.de 
ACE-String: xn--berall-ist-8db.de

**Comment by timmillwood** [comment]
I'm getting the same error and don't have a domain with a special character.
