### ISSUE TITLE
ERROR: Invalid CloudFlare Credentials - 400

### ISSUE THREAD

**Issue by drpaneas** [oznu/docker-cloudflare-ddns#58]
The API key is correct (tested with curl).
Why this can be happening?

**Comment by mdesson** [comment]
Did you figure out the issue? My API key stopped working

**Comment by AnthraxBP** [comment]
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-cloudflare-setup: executing...
----------------------------------------------------------------
ERROR: Invalid CloudFlare Credentials - 400
----------------------------------------------------------------
Make sure the API_KEY is correct. You can
get your scoped CloudFlare API Token here:
https://dash.cloudflare.com/profile/api-tokens

----------------------------------------------------------------
[cont-init.d] 30-cloudflare-setup: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 50-remove-record: executing...
[cont-finish.d] 50-remove-record: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-cloudflare-setup: executing...
----------------------------------------------------------------
ERROR: Invalid CloudFlare Credentials - 400
----------------------------------------------------------------
Make sure the API_KEY is correct. You can
get your scoped CloudFlare API Token here:
https://dash.cloudflare.com/profile/api-tokens

----------------------------------------------------------------
[cont-init.d] 30-cloudflare-setup: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 50-remove-record: executing...
[cont-finish.d] 50-remove-record: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-cloudflare-setup: executing...
----------------------------------------------------------------
ERROR: Invalid CloudFlare Credentials - 400
----------------------------------------------------------------
Make sure the API_KEY is correct. You can
get your scoped CloudFlare API Token here:
https://dash.cloudflare.com/profile/api-tokens

----------------------------------------------------------------
[cont-init.d] 30-cloudflare-setup: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 50-remove-record: executing...
[cont-finish.d] 50-remove-record: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-cloudflare-setup: executing...
----------------------------------------------------------------
ERROR: Invalid CloudFlare Credentials - 400
----------------------------------------------------------------
Make sure the API_KEY is correct. You can
get your scoped CloudFlare API Token here:
https://dash.cloudflare.com/profile/api-tokens

----------------------------------------------------------------
[cont-init.d] 30-cloudflare-setup: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 50-remove-record: executing...
[cont-finish.d] 50-remove-record: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.


i have try to use APIkey as a globalkey. still not work and I try as a token that enable zone editor still not work

I'm so frustrated whats wrong with it.
