### ISSUE TITLE
Invalid CloudFlare Credentials - 400

### ISSUE THREAD

**Issue by spicerackk** [oznu/docker-cloudflare-ddns#59]
I am following the instructions perfectly, I had it working but then had to rebuild the container. 

I have created a new API_KEY, pasted that in env using the variable "CLOUDFLAREAPIKEY" and yet I am still getting the above error. I have tried both creating a new token as well as using the global, and even changed the global with neither working. 

I am at a loss as to what is going on. 

Running in compose.

**Comment by spicerackk** [comment]
Fixed, was issue in compose file.

**Comment by balajeek** [comment]
I have the same error, can you tell us what you did to fix this?

**Comment by matthuisman** [comment]
you may need to do
```
    environment:
      - "API_KEY=[MY API KEY]"
      - "ZONE=[MY DOMAIN]"
      - "SUBDOMAIN=[MY SUBDOMAIN]"
```
Note the quotes on either side.

**Comment by AnthraxBP** [comment]
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-cloudflare-setup: executing...
----------------------------------------------------------------
ERROR: Invalid CloudFlare Credentials - 400
----------------------------------------------------------------
Make sure the API_KEY is correct. You can
get your scoped CloudFlare API Token here:
https://dash.cloudflare.com/profile/api-tokens

----------------------------------------------------------------
[cont-init.d] 30-cloudflare-setup: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 50-remove-record: executing...
[cont-finish.d] 50-remove-record: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-cloudflare-setup: executing...
----------------------------------------------------------------
ERROR: Invalid CloudFlare Credentials - 400
----------------------------------------------------------------
Make sure the API_KEY is correct. You can
get your scoped CloudFlare API Token here:
https://dash.cloudflare.com/profile/api-tokens

----------------------------------------------------------------
[cont-init.d] 30-cloudflare-setup: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 50-remove-record: executing...
[cont-finish.d] 50-remove-record: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-cloudflare-setup: executing...
----------------------------------------------------------------
ERROR: Invalid CloudFlare Credentials - 400
----------------------------------------------------------------
Make sure the API_KEY is correct. You can
get your scoped CloudFlare API Token here:
https://dash.cloudflare.com/profile/api-tokens

----------------------------------------------------------------
[cont-init.d] 30-cloudflare-setup: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 50-remove-record: executing...
[cont-finish.d] 50-remove-record: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-cloudflare-setup: executing...
----------------------------------------------------------------
ERROR: Invalid CloudFlare Credentials - 400
----------------------------------------------------------------
Make sure the API_KEY is correct. You can
get your scoped CloudFlare API Token here:
https://dash.cloudflare.com/profile/api-tokens

----------------------------------------------------------------
[cont-init.d] 30-cloudflare-setup: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 50-remove-record: executing...
[cont-finish.d] 50-remove-record: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.


i have try to use APIkey as a globalkey. still not work and I try as a token that enable zone editor still not work

I'm so frustrated whats wrong with it.

this is my command.

sudo docker run oznu/cloudflare-ddns \
  -e API_KEY=KlsFE-6c0d5d8b0b68ce9997b90676ad1bd6814d986 \
  -e PROXIED=true \
  -e EMAIL=master@bulletproftlink.ru \
  -e ZONE=bp.net.co \
  -e SUBDOMAIN=shop.bp.net.co \
  -e SUBDOMAIN=store.bp.net.co \
  -e RRTYPE=A \
  -e CRON="*/5 * * *" \
  -e DNS_SERVER=10.0.0.2

tell me if am wrong.

**Comment by cnavarro1499** [comment]
This happened to me when where the DDNS provider had the first letter of my email capitalized. (I typically never capitalize my email.) Everything worked once I had my email EXACTLY the same with matching case.
