### ISSUE TITLE
Cannot pull image

### ISSUE THREAD

**Issue by MyBlackMIDIScore** [oznu/docker-cloudflare-ddns#65]
When trying to make the container through Docker Compose it gives an error when it tries to pull the image:
`ERROR: pull access denied for onzu/cloudflare-ddns, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

I have used the 'docker login' command and logged in successfully and the image page is normally accessible on Docker Hub but I still get this error.

I can attach my docker-compose.yaml if you'd like but I doubt that the problem lies there.

Any help would be appreciated. Thanks in advance!

**Comment by oznu** [comment]
> onzu/cloudflare-ddns

that's not right.

**Comment by MyBlackMIDIScore** [comment]
Oh silly me. I guess thats what you get for not copy-pasting the image name.
Sorry for the trouble.
