### ISSUE TITLE
Unraid email address field is mandatory

### ISSUE THREAD

**Issue by ustrucx** [oznu/docker-cloudflare-ddns#67]
While there is a warning about NOT FILLING the email when using a scoped API in the documentation, the email field remains mandatory making it impossible to use it in Unraid with a scoped API.

What made me guess this is the problem on my setup was this message:

ERROR: Invalid CloudFlare Credentials - 400
----------------------------------------------------------------
Make sure the EMAIL and API_KEY variables are correct. You can
get your CloudFlare API Key here:
https://www.cloudflare.com/a/profile

If you are using a zone token please remove the EMAIL variable
from this container.

**Comment by RyanOver9000** [comment]
Merp4's solution worked for me. Thanks!
