### ISSUE TITLE
The ipinfo.io website is not accessible in China

### ISSUE THREAD

**Issue by le0liu** [oznu/docker-cloudflare-ddns#72]
I tested it on ping.pe. The IP of ipinfo.io is not accessible in China, and the real IP cannot be obtained after adding a proxy. Can I change a website that is not masked by GFW? Thank you very much.

**Comment by davidfregoli** [comment]
ipify should work as a drop-in replacement
`curl -sf4 "https://api.ipify.org/?format=json" | jq -r '.ip'`
