### ISSUE TITLE
ERROR: Failed to update CloudFlare DNS record

### ISSUE THREAD

**Issue by domqc** [oznu/docker-cloudflare-ddns#74]
Hi,
I keep getting: ERROR: Failed to update CloudFlare DNS record
I get the correct current and desired DNS, but it fail on update
Anything missing?

ddns API token summary:
All zones - Zone Settings:Read, Zone:Read, DNS:Edit

docker-compose:
version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: unless-stopped
    environment:
      - API_KEY=ddns API token
      - ZONE=example.com
      - PROXIED=true

log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 30-cloudflare-setup: executing... ,
DNS Zone: example.com,
DNS Record: example.com,
[cont-init.d] 30-cloudflare-setup: exited 0.,
[cont-init.d] 50-ddns: executing... ,
Updating CloudFlare DNS record example.com from 1.1.1.1 to 2.2.2.2...,
ERROR: Failed to update CloudFlare DNS record example.com from 1.1.1.1 to 2.2.2.2
crond: USER root pid 430 cmd /etc/cont-init.d/50-ddns
Updating CloudFlare DNS record example.com from 1.1.1.1 to 2.2.2.2...,
ERROR: Failed to update CloudFlare DNS record example.com from 1.1.1.1 to 2.2.2.2
.... running every 5 minutes with the same result

**Comment by nazzak** [comment]
Hi, 
I'm having the same issue.
I'm using the same config, and it manages to get the ip on my A record but it can't update it.

**Comment by nazzak** [comment]
I'm actually using a domain .tk which is not supported by Cloudflare API. Actually all freenom "free" domain names are not supported. 
see error I got : 
"You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."

**Comment by domqc** [comment]
Ah, I missed this in the API. That solve the issue. Thanks
