### ISSUE TITLE
How often is the DDNS check?

### ISSUE THREAD

**Issue by jwillmer** [oznu/docker-cloudflare-ddns#8]
Couldn't find it in the docs and can't interpret [`/usr/sbin/crond -f -l 8 -d 6`](https://github.com/oznu/docker-cloudflare-ddns/blob/5fc2d3603fe9d1d98e010f9eda66c89122b1d08a/root/etc/services.d/crond/run#L4).

**Feature request**: Custom time frame

**Comment by oznu** [comment]
https://github.com/oznu/docker-cloudflare-ddns/blob/master/root/etc/cont-init.d/30-cloudflare-setup#L77

Every 5 minutes.
