### ISSUE TITLE
cannot update wildcard * A record

### ISSUE THREAD

**Issue by michael-pellegrini** [oznu/docker-cloudflare-ddns#80]
Is it possible to update A record with name set as `*` ?

I can update the root domain example.com without issue. 
I'm trying to update the wildcard record but unable to, instead a new record is added when I specify `subdomain=*`

This does not work with cloudflare because the name has to be set as `*` and not `*.example.com`

**Comment by kosmonot** [comment]
For DDNS subdomains you create subdomains with CNAME records (with the domain name in the A record as the target).  Then everything changes to the new IP as soon as the A record is updated.

**Comment by kosmonot** [comment]
So you would have to either proxy everything or nothing on CloudFlare if you had a wildcard A record?

**Comment by michael-pellegrini** [comment]
Yes, I'm using a reverse proxy for all subdomains to conserve IP addresses. I only update the proxy when names are changed or added. Having the ability to update the wildcard A record would be beneficial to anyone using a reverse proxy.

**Comment by michael-pellegrini** [comment]
@favonia Started over with a fresh image and wildcard updates without issue.

**Comment by michael-pellegrini** [comment]
@favonia Thanks for the update. Work around is run two instances. Since only two records need updated.
