### ISSUE TITLE
Can I use multiple sub domains?

### ISSUE THREAD

**Issue by jwillmer** [oznu/docker-cloudflare-ddns#9]
I would like to update multiple sub domains like:

`SUBDOMAIN: nextcloud, home `

**Comment by oznu** [comment]
I use CNAMEs to achieve this as it 'just works' and doesn't add any complexity to the cloudflare-ddns scripts.

nextcloud.mydomain.com -> CNAME -> ddns.mydomain.com

**Comment by jwillmer** [comment]
Ah, so that `ddns` points to the same address as `nextcloud`. Neat!

**Comment by jwillmer** [comment]
You might add this trick to the README

**Comment by AbayefD** [comment]
If I use CNAME multiple domains what I need type in "-e SUBDOMAIN ..." ?

**Comment by jwillmer** [comment]
Can u try to be more specific about what your problem is? Maybe open a new issue with it and link to this one? This one is closed ;-)
